name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
      - feature/*
      - feature-*
  pull_request:
    branches:
      - main
      - dev
      - feature/*
      - feature-*

jobs:
  quality-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [eslint, prettier]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Format/Lint Task
        run: |
          if [ "${{ matrix.task }}" == "eslint" ]; then
            npx eslint . --fix
          elif [ "${{ matrix.task }}" == "prettier" ]; then
            npx prettier --write .
          fi
