name: Format Pipeline

on:
  push:
    branches:
      - dev
      - feature/*
  pull_request:
    branches:
      - dev
      - feature/*

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npx prettier --check

      - name: Fail if Prettier issues found
        run: |
          if [ $(git diff --exit-code); then echo "Prettier check passed."; exit 0; else echo "Prettier check failed. Run 'npm run format' to fix."; exit 1; fi